feat: adding first and last and adding addAttributes
emulsify-ds/compound pull request #41
Opened 2022-04-30 16:10 UTC by mndonx

**Summary**

This PR improves the Pager component for Compound.

- Adds First and Last option to Pager (this is regularly seen in Drupal sites)
- Adds `add_attributes` to template (to make it easier to extend them when we implement them in other components)
- Renamed `pager-ellipses.yml` to `pager-next-ellipses.yml` to match `prev` example for consistency
- Hid the ellipses on the basic pager example (it didn't seem to make sense to keep them in without the arrows there too.)

**How to review this PR**
- Check out `feat-pager` branch
- `npm run develop`
- Navigate to:
  http://localhost:6006/?path=/story/molecules-menus-pager--basic
  http://localhost:6006/?path=/story/molecules-menus-pager--with-next
  http://localhost:6006/?path=/story/molecules-menus-pager--with-both
  http://localhost:6006/?path=/story/molecules-menus-pager--with-previous
  http://localhost:6006/?path=/story/molecules-menus-pager--with-first-and-last
- Verify that changes above make sense and the code looks good

2022-08-30 14:21 UTC, callinmullaney commented on components/02-molecules/pager/pager.twig
> +  <nav {{ add_attributes(pager__attributes) }} aria-label="{{ pagination_id|default('Pagination'|t) }}">
@mndonx Just wanted to confirm Joe's feedback is valid and `aria-label` should be moved to the `add_attributes` function

2022-08-31 03:07 UTC, mndonx commented
@callinmullaney @joetower Thanks! I've moved the aria-label into the pager__attributes.

2022-09-16 14:48 UTC, joetower approved these changes
@mndonx This looks great! :clap: 

I think it's ready to review in our L10.

2022-09-29 17:56 UTC, ModulesUnraveled requested changes
- [ ] Let's use array numbers to get rid of `0`s.
- [ ] Make the current page more obvious, and add a `current` to each example.
- [ ] Add `aria-current="page"` to the current link.
- [ ] Please check to see what the Drupal text is for "first" and "last"
- [ ] You can remove all of the empty `attributes` from yaml files
- [ ] Add `role="navigation"` to the nav

2022-10-09 22:29 UTC, mndonx commented
@ModulesUnraveled 

> * [x]  Let's use array numbers to get rid of `0`s.
> * [x]  Make the current page more obvious, and add a `current` to each example.
> * [x]  Add `aria-current="page"` to the current link.
> * [x]  Please check to see what the Drupal text is for "first" and "last"
> * [x]  You can remove all of the empty `attributes` from yaml files
> * [x]  Add `role="navigation"` to the nav

Also:
- I removed yml references to `pager-uuid` -- I can't find this anywhere, and not sure why it was there. 
- I also stripped down the theming of the next/prev buttons. I feel like the css arrows are more of a design choice, and we're trying to avoid that here. 

Let me know what you think!
Amanda

2022-10-13 17:58 UTC, mndonx commented
Note to self to adjust item padding at small widths

2023-03-03 21:59 UTC, mcortes19 approved these changes

2023-03-10 17:26 UTC, mariannuar approved these changes
LGTM!

2023-03-14 15:22 UTC, merged