feat(social-menu): adjustments to social links, adding linked in
emulsify-ds/compound pull request #68
Opened 2022-11-29 06:58 UTC by mndonx

**Summary**

This PR makes small adjustments to the social links: 

- Adjusts extend formatting
- Adds LinkedIn icon
- Renames parent directory "social menu" (instead of "social")

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Part of initiative to solidify component markup.

**How to review this PR**

- [ ] Visit Social Menu component in Emulsify.
- [ ] Ensure that the markup is clean and easily repurposed.

2022-12-02 18:58 UTC, joetower approved these changes
@mndonx This looks good to me! Good call changing the name to `social-menu` as it's more descriptive and matches our other `*-menu` naming conventions. I think it's ready for group review. :+1:

2022-12-13 17:02 UTC, callinmullaney requested changes
See code comment for 1 small change.

2022-12-13 17:02 UTC, callinmullaney commented on components/02-molecules/menus/social-menu/_social-menu.scss
> +  height: 2rem;
Per our group discussion: Lets create an `$social-icon-size` size variable at the top of this file then set the height/width to that variable.

2023-01-19 19:34 UTC, mcortes19 approved these changes

2023-01-23 14:21 UTC, mcortes19 approved these changes

2023-01-23 14:51 UTC, callinmullaney approved these changes

2023-03-14 15:17 UTC, merged